### ISSUE TITLE
How about add CODE_OF_CONDUCT.md to Dr.Jekyll?

### ISSUE THREAD

**Issue by bbvch13531** [MoonCrystalPower/Dr.Jekyll#12]
Type of issue
 - Doc

Description
- I think opensource project should have code of conduct. How about add CODE_OF_CONDUCT.md to Dr.Jekyll?
You could add CODE_OF_CONDUCT.md below [link](https://github.com/MoonCrystalPower/Dr.Jekyll/community/code-of-conduct/new) 😄

**Comment by byeolbit** [comment]
We were planning to add it(ISSUE = #1), but it was in hold.
Thank you for your suggestion. 😄 
We just updated it.
